# config.yaml: define the parameters for the pipeline
img_feature_dim: 512
batch_size: 32
epochs: 5
device: cuda:1
learning_rate: 0.0001

dataset_path: /data/SunYang/datasets/Algonauts_dataset/algonauts_2023_main/algonauts_2023_challenge_data
pkl_path: /data/SunYang/datasets/Algonauts_dataset/pkl_clip
train_imgs_dir: training_split/training_images
train_imgs_feature_file: train_imgs_feature.npy
lh_fmri_dir: training_split/training_fmri/lh_training_fmri.npy
rh_fmri_dir: training_split/training_fmri/rh_training_fmri.npy
test_imgs_dir: test_split/test_images
test_imgs_feature_dir: test_imgs_feature.npy
parent_submission_dir: /data/SunYang/datasets/Algonauts_dataset/algonauts_2023_main/algonauts_2023_challenge_submission

is_save_checkpoint: 1
is_load_checkpoint: 1
checkpoint_path: /data/SunYang/models/competition/competition_4_algonauts/dev/checkpoint